---
name: "🔒 Harden Runner (Minimal)"
description: "Security Egress Audit using minimal profile"
runs:
  using: "composite"
  steps:
    - name: "🔒 Harden Runner"
      uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40
      with:
        egress-policy: block
        allowed-endpoints: >
          api.github.com:443
          github.com:443
          *.githubusercontent.com:443
          mise.run:443
          *.mise.jdx.dev:443
