// Copyright (c) 2026 SnowdreamTech. All rights reserved.
// Licensed under the MIT License. See LICENSE file in the project root for full license information.

// Package lockfile implements the unirtm.lock file format — a multi-platform
// snapshot of resolved tool versions, download URLs, and checksums.
//
// The format is TOML-based and intentionally compatible with the mise.lock
// schema so that projects can reuse the same lockfile understanding across tools.
//
// Example:
//
//	# @generated - this file is auto-generated by `unirtm lock`
//	[[tools.cli]]
//	version = "2.72.0"
//	backend = "github:cli/cli"
//
//	[tools.cli."platforms.linux-amd64"]
//	checksum = "sha256:abc123..."
//	size     = 12345678
//	url      = "https://github.com/cli/cli/releases/download/v2.72.0/gh_2.72.0_linux_amd64.tar.gz"
//	url_api  = "https://api.github.com/repos/cli/cli/releases/assets/123456"
package lockfile

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"sync"
	"time"

	"github.com/pelletier/go-toml/v2"
)

// Header is written at the top of every generated lockfile.
const Header = "# @generated - this file is auto-generated by `unirtm lock`\n" +
	"# Do not edit manually. See https://github.com/snowdreamtech/unirtm for details.\n"

// LockFile is the in-memory representation of a unirtm.lock file.
// It maps a canonical tool key to one or more ToolLockEntry records.
// Multiple entries per tool are an edge case (e.g. different options sets),
// mirroring the [[tools.name]] array-of-tables TOML syntax from mise.
type LockFile struct {
	// Tools maps a canonical key ("backend:tool") → list of entries.
	// In the common case there is exactly one entry per tool key.
	Tools map[string][]*ToolLockEntry `toml:"tools"`

	// mu protects concurrent access to Tools.
	mu sync.RWMutex

	// path is the filesystem path this lock file was read from / will be written to.
	path string

	// updatedAt records the last time this object was modified (for dirty tracking).
	updatedAt time.Time
}

// ToolLockEntry corresponds to one [[tools."<key>"]] TOML table.
type ToolLockEntry struct {
	// Version is the resolved, exact version string (e.g. "2.72.0").
	Version string `toml:"version"`

	// Backend is the backend name used to install this tool (e.g. "github", "ubi").
	Backend string `toml:"backend"`

	// Options holds backend-specific options that affect artifact selection,
	// e.g. {"exe": "rg", "matching": "musl"} for ubi.
	// omitempty so that empty maps are not serialised.
	Options map[string]string `toml:"options,omitempty"`

	// Platforms maps a platform key (e.g. "linux-amd64") to its artifact entry.
	// We use toml:"-" here because the mise format stores these as top-level
	// keys in the tool table with a "platforms." prefix, e.g. ["platforms.linux-amd64"].
	Platforms map[string]*PlatformEntry `toml:"-"`

	// RawEntries captures the mise-style flat keys during decoding.
	RawEntries map[string]any `toml:",inline"`
}

// PlatformEntry holds the resolved artifact metadata for a single platform.
type PlatformEntry struct {
	// Checksum is the hex digest with algorithm prefix: "sha256:<hex>" or "blake3:<hex>".
	// Empty when the backend does not provide checksums.
	Checksum string `toml:"checksum,omitempty"`

	// Size is the artifact size in bytes (0 = unknown).
	Size int64 `toml:"size,omitempty"`

	// URL is the direct download URL.
	URL string `toml:"url,omitempty"`

	// URLAPI is the backend API URL for the asset (GitHub Releases asset API, etc.).
	// Stored for cache-bypass installs that need the canonical API reference.
	URLAPI string `toml:"url_api,omitempty"`
}

// ─── Construction ─────────────────────────────────────────────────────────────

// New returns an empty LockFile bound to path.
func New(path string) *LockFile {
	return &LockFile{
		Tools: make(map[string][]*ToolLockEntry),
		path:  path,
	}
}

// Load reads and parses path as a unirtm.lock TOML file.
// Returns a new empty LockFile (not an error) when path does not exist,
// which allows callers to handle the "first run" case uniformly.
func Load(path string) (*LockFile, error) {
	lf := New(path)

	data, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return lf, nil // first run — no lockfile yet
	}
	if err != nil {
		return nil, fmt.Errorf("lockfile: read %q: %w", path, err)
	}

	// Strip the header comment before TOML-decoding.
	content := stripHeader(string(data))

	if err := toml.Unmarshal([]byte(content), lf); err != nil {
		return nil, fmt.Errorf("lockfile: parse %q: %w", path, err)
	}

	// Ensure nil maps become empty maps after decode.
	if lf.Tools == nil {
		lf.Tools = make(map[string][]*ToolLockEntry)
	}
	for _, entries := range lf.Tools {
		for _, e := range entries {
			if e == nil {
				continue
			}
			if e.Platforms == nil {
				e.Platforms = make(map[string]*PlatformEntry)
			}
			// Migrate flat "platforms.<plat>" keys into the Platforms map.
			for k, v := range e.RawEntries {
				if strings.HasPrefix(k, "platforms.") {
					platKey := strings.TrimPrefix(k, "platforms.")
					// Re-decode the map into a PlatformEntry
					if peData, ok := v.(map[string]any); ok {
						pe := &PlatformEntry{}
						if b, err := toml.Marshal(peData); err == nil {
							_ = toml.Unmarshal(b, pe)
							e.Platforms[platKey] = pe
						}
					}
				}
			}
			e.RawEntries = nil // clean up
		}
	}

	return lf, nil
}

// ─── Persistence ──────────────────────────────────────────────────────────────

// Save serialises the LockFile to its bound path atomically (write-temp + rename).
func (lf *LockFile) Save() error {
	if err := os.MkdirAll(filepath.Dir(lf.path), 0755); err != nil {
		return fmt.Errorf("lockfile: mkdir: %w", err)
	}

	var buf bytes.Buffer
	buf.WriteString(Header)
	buf.WriteByte('\n')

	lf.mu.RLock()
	keys := sortedKeys(lf.Tools)
	lf.mu.RUnlock()

	for _, key := range keys {
		lf.mu.RLock()
		entries := lf.Tools[key]
		lf.mu.RUnlock()

		for _, entry := range entries {
			if entry == nil {
				continue
			}
			// Write [[tools."<key>"]] header and scalar fields manually so that
			// platform sub-tables appear in the expected position.
			if err := lf.encodeEntry(&buf, key, entry); err != nil {
				return fmt.Errorf("lockfile: encode %q: %w", key, err)
			}
		}
	}

	// Atomic write: temp file → rename.
	tmp := lf.path + ".tmp"
	if err := os.WriteFile(tmp, buf.Bytes(), 0644); err != nil {
		return fmt.Errorf("lockfile: write temp: %w", err)
	}
	if err := os.Rename(tmp, lf.path); err != nil {
		_ = os.Remove(tmp)
		return fmt.Errorf("lockfile: rename: %w", err)
	}

	return nil
}

// encodeEntry writes a single tool entry in the canonical TOML format.
func (lf *LockFile) encodeEntry(buf *bytes.Buffer, key string, e *ToolLockEntry) error {
	if e == nil {
		return nil
	}
	// [[tools."<key>"]]
	buf.WriteString(fmt.Sprintf("[[tools.%q]]\n", key))
	buf.WriteString(fmt.Sprintf("version = %q\n", e.Version))
	buf.WriteString(fmt.Sprintf("backend = %q\n", e.Backend))

	if len(e.Options) > 0 {
		// Inline table for options: options = { exe = "rg" }
		var opts []string
		for _, pair := range sortedMapEntries(e.Options) {
			opts = append(opts, fmt.Sprintf("%s = %q", pair.k, pair.v))
		}
		buf.WriteString(fmt.Sprintf("options = { %s }\n", strings.Join(opts, ", ")))
	}

	buf.WriteByte('\n')

	// Platform sub-tables sorted for determinism.
	platKeys := sortedKeys(e.Platforms)
	for _, pk := range platKeys {
		pe := e.Platforms[pk]
		// Write as [tools.key."platforms.linux-amd64"] to match mise format.
		buf.WriteString(fmt.Sprintf("[tools.%q.%q]\n", key, "platforms."+pk))
		if pe.Checksum != "" {
			buf.WriteString(fmt.Sprintf("checksum = %q\n", pe.Checksum))
		}
		if pe.Size > 0 {
			buf.WriteString(fmt.Sprintf("size = %d\n", pe.Size))
		}
		if pe.URL != "" {
			buf.WriteString(fmt.Sprintf("url = %q\n", pe.URL))
		}
		if pe.URLAPI != "" {
			buf.WriteString(fmt.Sprintf("url_api = %q\n", pe.URLAPI))
		}
		buf.WriteByte('\n')
	}

	return nil
}

// ─── Query API ────────────────────────────────────────────────────────────────

// GetEntry returns the first ToolLockEntry for key that matches the given version.
// GetEntry returns the ToolLockEntry for a given key and version.
// If version is empty, any version matches. Returns nil when not found.
func (lf *LockFile) GetEntry(key, version string) *ToolLockEntry {
	lf.mu.RLock()
	defer lf.mu.RUnlock()

	for _, e := range lf.Tools[key] {
		if e == nil {
			continue
		}
		if version == "" || e.Version == version {
			return e
		}
	}
	return nil
}

// GetPlatform returns the PlatformEntry for (key, version, platformKey).
// Returns nil when not found.
func (lf *LockFile) GetPlatform(key, version, platformKey string) *PlatformEntry {
	e := lf.GetEntry(key, version)
	if e == nil {
		return nil
	}
	return e.Platforms[platformKey]
}

// HasURL reports whether the lockfile contains a download URL for the given
// (key, version, platformKey) combination. Used by strict-mode enforcement.
func (lf *LockFile) HasURL(key, version, platformKey string) bool {
	pe := lf.GetPlatform(key, version, platformKey)
	return pe != nil && pe.URL != ""
}

// IsEmpty returns true when no tools are recorded in the lockfile.
func (lf *LockFile) IsEmpty() bool {
	lf.mu.RLock()
	defer lf.mu.RUnlock()
	return len(lf.Tools) == 0
}

// Path returns the filesystem path this LockFile is bound to.
func (lf *LockFile) Path() string { return lf.path }

// ─── Mutation API ─────────────────────────────────────────────────────────────

// UpsertEntry creates or updates the ToolLockEntry for key+version.
// If an entry for key+version already exists it is updated in place;
// otherwise a new entry is appended to lf.Tools[key].
func (lf *LockFile) UpsertEntry(key string, entry *ToolLockEntry) {
	if entry == nil {
		return
	}
	lf.mu.Lock()
	defer lf.mu.Unlock()

	entries := lf.Tools[key]
	for i, e := range entries {
		if e == nil {
			continue
		}
		if e.Version == entry.Version {
			lf.Tools[key][i] = entry
			lf.updatedAt = time.Now()
			return
		}
	}
	lf.Tools[key] = append(entries, entry)
	lf.updatedAt = time.Now()
}

// UpsertPlatform creates or updates a single PlatformEntry inside an existing
// (or newly created) ToolLockEntry.
func (lf *LockFile) UpsertPlatform(key, version, platformKey string, pe *PlatformEntry) {
	lf.mu.Lock()
	defer lf.mu.Unlock()

	var e *ToolLockEntry
	for _, entry := range lf.Tools[key] {
		if entry != nil && entry.Version == version {
			e = entry
			break
		}
	}

	if e == nil {
		e = &ToolLockEntry{
			Version:   version,
			Platforms: make(map[string]*PlatformEntry),
		}
		lf.Tools[key] = append(lf.Tools[key], e)
	}

	if e.Platforms == nil {
		e.Platforms = make(map[string]*PlatformEntry)
	}
	e.Platforms[platformKey] = pe
	lf.updatedAt = time.Now()
}

// RemoveEntry removes all entries for key (tool eviction, e.g. after uninstall).
func (lf *LockFile) RemoveEntry(key string) {
	lf.mu.Lock()
	defer lf.mu.Unlock()
	delete(lf.Tools, key)
	lf.updatedAt = time.Now()
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

// ToolKey builds the canonical lock key for a given backend+tool combination.
//
//	ToolKey("github", "cli/cli")   → "github:cli/cli"
//	ToolKey("npm",    "typescript") → "npm:typescript"
func ToolKey(backendName, toolName string) string {
	return backendName + ":" + toolName
}

// stripHeader removes the generated-file comment header from raw TOML content.
func stripHeader(content string) string {
	var lines []string
	for _, line := range strings.Split(content, "\n") {
		if strings.HasPrefix(line, "#") || strings.TrimSpace(line) == "" {
			continue
		}
		lines = append(lines, line)
	}
	return strings.Join(lines, "\n")
}

// sortedKeys returns the keys of any map[string]T in ascending order.
func sortedKeys[T any](m map[string]T) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// sortedMapEntries returns key-value pairs of a map[string]string sorted by key.
func sortedMapEntries(m map[string]string) []struct{ k, v string } {
	keys := sortedKeys(m)
	out := make([]struct{ k, v string }, len(keys))
	for i, k := range keys {
		out[i] = struct{ k, v string }{k, m[k]}
	}
	return out
}
