// Copyright 2018 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Ported from github.com/google/addlicense v1.2.0 (main_test.go).
// Package renamed from main to addlicense; spdxFlag constants renamed to SpdxFlag.
package addlicense

import (
	"io/ioutil" //nolint:staticcheck
	"os"
	"testing"
	"text/template"
)

// createTempFile creates a temporary file with the specified contents and
// pattern. The caller is responsible for deleting the file when done.
func createTempFile(contents string, pattern string) (*os.File, error) {
	f, err := ioutil.TempFile("", pattern)
	if err != nil {
		return nil, err
	}

	if err := ioutil.WriteFile(f.Name(), []byte(contents), 0644); err != nil {
		return nil, err
	}

	return f, nil
}

func TestAddLicense(t *testing.T) {
	tmpl := template.Must(template.New("").Parse("{{.Holder}}{{.Year}}{{.SPDXID}}"))
	data := licenseData{Holder: "H", Year: "Y", SPDXID: "S"}

	tests := []struct {
		contents     string
		wantContents string
		wantUpdated  bool
	}{
		{"", "// HYS\n\n", true},
		{"content", "// HYS\n\ncontent", true},

		// various headers that should be left intact. Many don't make
		// sense for our temp file extension, but that doesn't matter.
		{"#!/bin/bash\ncontent", "#!/bin/bash\n// HYS\n\ncontent", true},
		{"<?xml version='1.0'?>\ncontent", "<?xml version='1.0'?>\n// HYS\n\ncontent", true},
		{"<!doctype html>\ncontent", "<!doctype html>\n// HYS\n\ncontent", true},
		{"<!DOCTYPE HTML>\ncontent", "<!DOCTYPE HTML>\n// HYS\n\ncontent", true},
		{"# encoding: UTF-8\ncontent", "# encoding: UTF-8\n// HYS\n\ncontent", true},
		{"# frozen_string_literal: true\ncontent", "# frozen_string_literal: true\n// HYS\n\ncontent", true},
		{"#\\ -w -p 8765\ncontent", "#\\ -w -p 8765\n// HYS\n\ncontent", true},
		{"<?php\ncontent", "<?php\n// HYS\n\ncontent", true},
		{"# escape: `\ncontent", "# escape: `\n// HYS\n\ncontent", true},
		{"# syntax: docker/dockerfile:1.3\ncontent", "# syntax: docker/dockerfile:1.3\n// HYS\n\ncontent", true},

		// ensure files with existing license or generated files are skipped.
		{"// Copyright 2000 Acme\ncontent", "// Copyright 2000 Acme\ncontent", false},
		{"// Code generated by go generate; DO NOT EDIT.\ncontent", "// Code generated by go generate; DO NOT EDIT.\ncontent", false},
	}

	for _, tt := range tests {
		f, err := createTempFile(tt.contents, "*.go")
		if err != nil {
			t.Error(err)
		}
		fi, err := f.Stat()
		if err != nil {
			t.Error(err)
		}

		updated, err := addLicense(f.Name(), fi.Mode(), tmpl, data)
		if err != nil {
			t.Error(err)
		}

		if updated != tt.wantUpdated {
			t.Errorf("addLicense with contents %q returned updated: %t, want %t", tt.contents, updated, tt.wantUpdated)
		}
		gotContents, err := ioutil.ReadFile(f.Name())
		if err != nil {
			t.Error(err)
		}
		if got := string(gotContents); got != tt.wantContents {
			t.Errorf("addLicense with contents %q returned contents: %q, want %q", tt.contents, got, tt.wantContents)
		}

		if !t.Failed() {
			_ = os.Remove(f.Name())
		}
	}
}

// TestLicenseHeader tests that license headers are added using the appropriate
// prefix for different filenames and extensions.
func TestLicenseHeader(t *testing.T) {
	tpl := template.Must(template.New("").Parse("{{.Holder}}{{.Year}}{{.SPDXID}}"))
	data := licenseData{Holder: "H", Year: "Y", SPDXID: "S"}

	tests := []struct {
		paths []string
		want  string
	}{
		{
			[]string{
				"f.unknown",
				"f.jpg",
				"README",
			},
			"",
		},
		{
			[]string{
				"f.c", "f.h",
				"f.gv",
				"f.java",
				"f.kt", "f.kts",
				"f.scala",
			},
			"/*\n * HYS\n */\n\n",
		},
		{
			[]string{
				"f.css", "f.scss", "f.sass", "f.less",
				"f.js", "f.mjs", "f.cjs", "f.jsx",
				"f.ts", "f.tsx",
			},
			"/**\n * HYS\n */\n\n",
		},
		{
			[]string{
				"f.cc", "f.cpp", "f.hh", "f.hpp",
				"f.cs",
				"f.dart",
				"f.go",
				"f.groovy",
				"f.gradle",
				"f.hcl",
				"f.m", "f.mm",
				"f.php",
				"f.proto",
				"f.rs",
				"f.swift",
				"f.v", "f.sv",
			},
			"// HYS\n\n",
		},
		{
			[]string{
				"f.awk",
				"f.buckconfig", "buck",
				"f.bzl", "f.bazel", "build", "f.build",
				"f.dockerfile", "dockerfile",
				"f.ex", "f.exs",
				"f.graphql",
				"f.jl",
				"f.nix",
				"f.pl",
				"f.pp",
				"f.py", "f.pyx", "f.pxd",
				"f.raku",
				"f.rb", "f.ru", "gemfile",
				"f.sh", "f.bash", "f.zsh",
				"f.tcl",
				"f.tf",
				"f.toml",
				"f.yaml", "f.yml",
			},
			"# HYS\n\n",
		},
		{
			[]string{
				"f.el",
				"f.lisp",
				"f.scm",
			},
			";; HYS\n\n",
		},
		{
			[]string{
				"f.erl",
			},
			"% HYS\n\n",
		},
		{
			[]string{
				"f.hs",
				"f.lua",
				"f.sql", "f.sdl",
			},
			"-- HYS\n\n",
		},
		{
			[]string{
				"f.html", "f.htm",
				"f.vue",
				"f.xml",
				"f.wxi", "f.wxl", "f.wxs",
			},
			"<!--\n HYS\n-->\n\n",
		},
		{
			[]string{
				".j2",
			},
			"{#\nHYS\n#}\n\n",
		},
		{
			[]string{
				"f.ml", "f.mli", "f.mll", "f.mly",
			},
			"(**\n   HYS\n*)\n\n",
		},
		{
			[]string{
				"f.ps1", "f.psm1",
			},
			"<#\n HYS\n#>\n\n",
		},
		{
			[]string{
				"f.vim",
			},
			"\" HYS\n\n",
		},
		{
			[]string{
				"cmakelists.txt", "f.cmake.in", "f.cmake",
			},
			"# HYS\n\n",
		},
		// ensure matches are case insensitive
		{
			[]string{
				"F.PY",
				"BUILD",
				"DoCkErFiLe",
			},
			"# HYS\n\n",
		},
	}

	for _, tt := range tests {
		for _, path := range tt.paths {
			header, _ := licenseHeader(path, tpl, data)
			if got := string(header); got != tt.want {
				t.Errorf("licenseHeader(%q) returned: %q, want: %q", path, got, tt.want)
			}
		}
	}
}

// TestIsGenerated tests that generated files are properly recognized.
func TestIsGenerated(t *testing.T) {
	tests := []struct {
		content string
		want    bool
	}{
		{"", false},
		{"Generated", false},
		{"// Code generated by go generate; DO NOT EDIT.", true},
		{"/*\n* Code generated by go generate; DO NOT EDIT.\n*/\n", true},
		{"DO NOT EDIT! Replaced on runs of cargo-raze", true},
	}

	for _, tt := range tests {
		b := []byte(tt.content)
		if got := isGenerated(b); got != tt.want {
			t.Errorf("isGenerated(%q) returned %v, want %v", tt.content, got, tt.want)
		}
	}
}

// TestHasLicense tests that existing license headers are identified.
func TestHasLicense(t *testing.T) {
	tests := []struct {
		content string
		want    bool
	}{
		{"", false},
		{"This is my license", false},
		{"This code is released into the public domain.", false},
		{"SPDX: MIT", false},

		{"Copyright 2000", true},
		{"CoPyRiGhT 2000", true},
		{"Subject to the terms of the Mozilla Public License", true},
		{"SPDX-License-Identifier: MIT", true},
		{"spdx-license-identifier: MIT", true},
	}

	for _, tt := range tests {
		b := []byte(tt.content)
		if got := hasLicense(b); got != tt.want {
			t.Errorf("hasLicense(%q) returned %v, want %v", tt.content, got, tt.want)
		}
	}
}

func TestFileMatches(t *testing.T) {
	tests := []struct {
		pattern   string
		path      string
		wantMatch bool
	}{
		// basic single directory patterns
		{"", "file.c", false},
		{"*.c", "file.h", false},
		{"*.c", "file.c", true},

		// subdirectory patterns
		{"*.c", "vendor/file.c", false},
		{"**/*.c", "vendor/file.c", true},
		{"vendor/**", "vendor/file.c", true},
		{"vendor/**/*.c", "vendor/file.c", true},
		{"vendor/**/*.c", "vendor/a/b/file.c", true},

		// single character "?" match
		{"*.?", "file.c", true},
		{"*.?", "file.go", false},
		{"*.??", "file.c", false},
		{"*.??", "file.go", true},

		// character classes - sets and ranges
		{"*.[ch]", "file.c", true},
		{"*.[ch]", "file.h", true},
		{"*.[ch]", "file.ch", false},
		{"*.[a-z]", "file.c", true},
		{"*.[a-z]", "file.h", true},
		{"*.[a-z]", "file.go", false},
		{"*.[a-z]", "file.R", false},

		// character classes - negations
		{"*.[^ch]", "file.c", false},
		{"*.[^ch]", "file.h", false},
		{"*.[^ch]", "file.R", true},
		{"*.[!ch]", "file.c", false},
		{"*.[!ch]", "file.h", false},
		{"*.[!ch]", "file.R", true},

		// comma-separated alternative matches
		{"*.{c,go}", "file.c", true},
		{"*.{c,go}", "file.go", true},
		{"*.{c,go}", "file.h", false},

		// negating alternative matches
		{"*.[^{c,go}]", "file.c", false},
		{"*.[^{c,go}]", "file.go", false},
		{"*.[^{c,go}]", "file.h", true},
	}

	for _, tt := range tests {
		patterns := []string{tt.pattern}
		if got := fileMatches(tt.path, patterns); got != tt.wantMatch {
			t.Errorf("fileMatches(%q, %q) returned %v, want %v", tt.path, patterns, got, tt.wantMatch)
		}
	}
}
