package hook

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
)

const bridgeScript = `#!/bin/sh
# Code generated by UniRTM; DO NOT EDIT.

# Load environment for GUI Git clients (Sourcetree, GitHub Desktop)
if [ -f ~/.profile ]; then . ~/.profile; fi
if [ -f ~/.bashrc ]; then . ~/.bashrc; fi

if command -v unirtm >/dev/null 2>&1; then
    exec unirtm hook run "$(basename "$0")" "$@"
else
    echo "⚠️ UniRTM not found in PATH. Skipping hook."
    exit 0
fi
`

// InstallBridgeScript writes the standard UniRTM bridge script to .git/hooks/
func InstallBridgeScript(ctx context.Context, dir string, hookName string) error {
	gitDir := filepath.Join(dir, ".git", "hooks")
	if _, err := os.Stat(gitDir); os.IsNotExist(err) {
		return fmt.Errorf(".git/hooks directory not found in %s", dir)
	}

	hookPath := filepath.Join(gitDir, hookName)
	
	// Create or overwrite the hook
	err := os.WriteFile(hookPath, []byte(bridgeScript), 0755)
	if err != nil {
		return fmt.Errorf("failed to write git hook %s: %w", hookName, err)
	}

	return nil
}
