package hook

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

const bridgeScript = `#!/bin/sh
# Code generated by UniRTM; DO NOT EDIT.

# Load environment for GUI Git clients (Sourcetree, GitHub Desktop)
if [ -f ~/.profile ]; then . ~/.profile; fi
if [ -f ~/.bashrc ]; then . ~/.bashrc; fi

if command -v unirtm >/dev/null 2>&1; then
    exec unirtm hook run "$(basename "$0")" "$@"
else
    echo "⚠️ UniRTM not found in PATH. Skipping hook."
    exit 0
fi
`

// InstallBridgeScript writes the standard UniRTM bridge script to .git/hooks/
func InstallBridgeScript(ctx context.Context, dir string, hookName string) error {
	cmd := exec.CommandContext(ctx, "git", "rev-parse", "--git-path", "hooks")
	cmd.Dir = dir
	out, err := cmd.Output()
	if err != nil {
		return fmt.Errorf("failed to resolve git hooks directory: %w", err)
	}

	hooksDir := strings.TrimSpace(string(out))
	if !filepath.IsAbs(hooksDir) {
		hooksDir = filepath.Join(dir, hooksDir)
	}

	if _, err := os.Stat(hooksDir); os.IsNotExist(err) {
		if err := os.MkdirAll(hooksDir, 0755); err != nil {
			return fmt.Errorf("git hooks directory does not exist and could not be created: %w", err)
		}
	}

	hookPath := filepath.Join(hooksDir, hookName)
	
	// Create or overwrite the hook
	err = os.WriteFile(hookPath, []byte(bridgeScript), 0755)
	if err != nil {
		return fmt.Errorf("failed to write git hook %s: %w", hookName, err)
	}

	return nil
}
