// Copyright (c) 2026 SnowdreamTech. All rights reserved.
// Licensed under the MIT License. See LICENSE file in the project root for full license information.

package cmd

import (
	"bytes"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"

	"github.com/snowdreamtech/unirtm/internal/cli/output"
	"github.com/spf13/cobra"
)

var (
	depTargetBranch   string
	depPrLimit        int
	depCooldownDays   int
	depUpdateInterval string
	depUpdateDay      string
	depDryRun         bool
)

var generateDependabotCmd = &cobra.Command{
	Use:   "dependabot",
	Short: "Auto-generate dependabot.yml from detected ecosystems",
	Args:  cobra.NoArgs,
	RunE:  runGenerateDependabot,
}

func init() {
	generateDependabotCmd.Flags().StringVarP(&generateOutput, "output", "o", "", "write to file instead of stdout")
	generateDependabotCmd.Flags().StringVar(&depTargetBranch, "target-branch", "dev", "Target branch for PRs")
	generateDependabotCmd.Flags().IntVar(&depPrLimit, "pr-limit", 5, "Max open PRs per ecosystem")
	generateDependabotCmd.Flags().IntVar(&depCooldownDays, "cooldown", 7, "Days to wait before updating")
	generateDependabotCmd.Flags().StringVar(&depUpdateInterval, "interval", "weekly", "Update frequency")
	generateDependabotCmd.Flags().StringVar(&depUpdateDay, "day", "monday", "Day of week for updates")
	generateDependabotCmd.Flags().BoolVar(&depDryRun, "dry-run", false, "Show what would be generated without writing")

	generateCmd.AddCommand(generateDependabotCmd)
}

type DepEntry struct {
	Ecosystem    string
	Directory    string
	TargetBranch string
	PrLimit      int
	Interval     string
	Day          string
	Cooldown     int
	Prefix       string
	Labels       []string
}

func runGenerateDependabot(cmd *cobra.Command, args []string) error {
	formatter := output.NewFormatter(output.FormatterOptions{
		Format:  getOutputFormat(),
		NoColor: false,
		Writer:  os.Stdout,
		Quiet:   quiet,
	})

	entries := scanForEcosystems()

	if len(entries) == 0 {
		formatter.Warning("No ecosystems detected. Ensure manifest files exist.", nil)
	}

	tmplStr := `---
# Dependabot Version Updates (Auto-generated by unirtm generate dependabot)
#
# ⚠️  DO NOT EDIT MANUALLY — This file is regenerated automatically.
# To update, run: unirtm generate dependabot --output .github/dependabot.yml
#
# Purpose: Automatically maintains project dependencies to ensure security and stability.

version: 2
updates:{{range .}}
  - package-ecosystem: "{{.Ecosystem}}"
    directory: "{{.Directory}}"
    target-branch: "{{.TargetBranch}}"
    open-pull-requests-limit: {{.PrLimit}}
    rebase-strategy: "auto"
    groups:
      all-dependencies:
        patterns: ["*"]
        update-types:
          - "patch"
          - "minor"
          - "major"
    schedule:
      interval: "{{.Interval}}"
      day: "{{.Day}}"
    cooldown:
      default-days: {{.Cooldown}}
    commit-message:
      prefix: "{{.Prefix}}"
    labels:{{range .Labels}}
      - "{{.}}"{{end}}
{{end}}`

	tmpl, err := template.New("dependabot").Parse(tmplStr)
	if err != nil {
		return err
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, entries); err != nil {
		return err
	}

	if depDryRun {
		fmt.Println("# [DRY-RUN] Would write to dependabot.yml:")
		fmt.Println(buf.String())
		return nil
	}

	if generateOutput == "" {
		fmt.Print(buf.String())
		return nil
	}

	dir := filepath.Dir(generateOutput)
	if dir != "" && dir != "." {
		if err := os.MkdirAll(dir, 0755); err != nil {
			return err
		}
	}

	if err := os.WriteFile(generateOutput, buf.Bytes(), 0644); err != nil {
		formatter.Error(fmt.Sprintf("Failed to write %s: %v", generateOutput, err))
		return err
	}

	formatter.Success(fmt.Sprintf("Generated %s successfully with %d ecosystems detected.", generateOutput, len(entries)), nil)
	return nil
}

func scanForEcosystems() []DepEntry {
	emitted := make(map[string]bool)
	var entries []DepEntry

	emit := func(ecosystem, directory string) {
		// Clean directory for dependabot format (must start with /)
		directory = filepath.ToSlash(directory)
		if directory == "." || directory == "" {
			directory = "/"
		} else if !strings.HasPrefix(directory, "/") {
			directory = "/" + directory
		}

		key := ecosystem + ":" + directory
		if emitted[key] {
			return
		}
		emitted[key] = true

		prefix := "chore(deps):"
		label := getEcosystemLabel(ecosystem)
		labels := []string{"dependencies", label}

		switch ecosystem {
		case "github-actions":
			prefix = "ci(deps):"
			labels = append(labels, "devops")
		case "docker", "devcontainers":
			prefix = "build(deps):"
			labels = append(labels, "infrastructure")
		case "pre-commit":
			labels = append(labels, "linting")
		}

		entries = append(entries, DepEntry{
			Ecosystem:    ecosystem,
			Directory:    directory,
			TargetBranch: depTargetBranch,
			PrLimit:      depPrLimit,
			Interval:     depUpdateInterval,
			Day:          depUpdateDay,
			Cooldown:     depCooldownDays,
			Prefix:       prefix,
			Labels:       labels,
		})
	}

	// 1. Check Root Singletons
	if hasFiles(".github/workflows", ".yml", ".yaml") {
		emit("github-actions", "/")
	}
	if fileExists(".gitmodules") {
		emit("gitsubmodule", "/")
	}
	if fileExists(".pre-commit-config.yaml") {
		emit("pre-commit", "/")
	}
	if fileExists("rust-toolchain") || fileExists("rust-toolchain.toml") {
		emit("rust-toolchain", "/")
	}
	if fileExists(".devcontainer.json") || fileExists(".devcontainer/devcontainer.json") || hasSubdirFiles(".devcontainer", "devcontainer.json") {
		emit("devcontainers", "/")
	}

	// 2. Walk tree for standard ecosystems
	_ = filepath.WalkDir(".", func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return nil
		}

		name := d.Name()
		if d.IsDir() {
			if name == ".git" || name == "node_modules" || name == "vendor" || name == ".terraform" || name == "testdata" || name == "fixtures" {
				return filepath.SkipDir
			}
			return nil
		}

		dir := filepath.Dir(path)
		ext := filepath.Ext(name)

		switch name {
		case "package.json":
			emit("npm", dir)
		case "requirements.txt", "requirements-dev.txt", "setup.py", "setup.cfg", "Pipfile":
			emit("pip", dir)
		case "go.mod":
			emit("gomod", dir)
		case "Cargo.toml":
			emit("cargo", dir)
		case "composer.json":
			emit("composer", dir)
		case "Gemfile":
			emit("bundler", dir)
		case "Dockerfile":
			emit("docker", dir)
		case "docker-compose.yml", "docker-compose.yaml":
			emit("docker", dir)
		case "mix.exs":
			emit("mix", dir)
		case "elm.json":
			emit("elm", dir)
		case "build.gradle", "build.gradle.kts":
			emit("gradle", dir)
		case "pom.xml":
			emit("maven", dir)
		case "packages.config":
			emit("nuget", dir)
		case "pubspec.yaml":
			emit("pub", dir)
		case "Package.swift":
			emit("swift", dir)
		case "WORKSPACE", "MODULE.bazel":
			emit("bazel", dir)
		case "bun.lockb", "bunfig.toml":
			emit("bun", dir)
		case "environment.yml", "environment.yaml":
			emit("conda", dir)
		case "Chart.yaml":
			emit("helm", dir)
		case "Project.toml":
			emit("julia", dir)
		case "uv.lock":
			emit("uv", dir)
		case "vcpkg.json":
			emit("vcpkg", dir)
		case "global.json":
			emit("dotnet-sdk", dir)
		}

		switch ext {
		case ".tf":
			emit("terraform", dir)
		case ".csproj", ".fsproj":
			emit("nuget", dir)
		}

		if strings.HasPrefix(name, "Dockerfile.") {
			emit("docker", dir)
		}

		return nil
	})

	// Sort entries for deterministic output
	sort.Slice(entries, func(i, j int) bool {
		if entries[i].Ecosystem == entries[j].Ecosystem {
			return entries[i].Directory < entries[j].Directory
		}
		return entries[i].Ecosystem < entries[j].Ecosystem
	})

	return entries
}

func getEcosystemLabel(ecosystem string) string {
	switch ecosystem {
	case "github-actions":
		return "github-actions"
	case "npm", "bun":
		return "javascript"
	case "pip", "conda", "uv":
		return "python"
	case "gomod":
		return "go"
	case "cargo", "rust-toolchain":
		return "rust"
	case "composer":
		return "php"
	case "bundler":
		return "ruby"
	case "docker":
		return "docker"
	case "mix":
		return "elixir"
	case "elm":
		return "elm"
	case "gitsubmodule":
		return "git"
	case "gradle", "maven":
		return "java"
	case "nuget", "dotnet-sdk":
		return "dotnet"
	case "pub":
		return "dart"
	case "swift":
		return "swift"
	case "terraform", "opentofu":
		return "terraform"
	case "devcontainers":
		return "devcontainers"
	case "bazel":
		return "bazel"
	case "helm":
		return "kubernetes"
	case "julia":
		return "julia"
	case "pre-commit":
		return "pre-commit"
	case "vcpkg":
		return "cpp"
	default:
		return "other"
	}
}

func fileExists(path string) bool {
	info, err := os.Stat(path)
	return err == nil && !info.IsDir()
}

func hasFiles(dir string, exts ...string) bool {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return false
	}
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		for _, ext := range exts {
			if strings.HasSuffix(e.Name(), ext) {
				return true
			}
		}
	}
	return false
}

func hasSubdirFiles(parentDir, filename string) bool {
	entries, err := os.ReadDir(parentDir)
	if err != nil {
		return false
	}
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		if fileExists(filepath.Join(parentDir, e.Name(), filename)) {
			return true
		}
	}
	return false
}
