// Copyright (c) 2026 SnowdreamTech. All rights reserved.
// Licensed under the MIT License. See LICENSE file in the project root for full license information.

// Package service provides business logic for UniRTM operations.
package service

import (
	"bufio"
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/pelletier/go-toml/v2"
	"github.com/snowdreamtech/unirtm/internal/config"
	"github.com/snowdreamtech/unirtm/internal/pkg/logger"
)

// MigrationSource represents the source format of a migration.
type MigrationSource string

const (
	// MigrationSourceMiseToml represents a .mise.toml file.
	MigrationSourceMiseToml MigrationSource = "mise.toml"
	// MigrationSourceToolVersions represents an asdf/mise .tool-versions file.
	MigrationSourceToolVersions MigrationSource = ".tool-versions"
)

// MigrationTool represents a single tool discovered during migration.
type MigrationTool struct {
	Name     string
	Version  string
	Backend  string
	Provider string
	Source   MigrationSource
}

// MigrationReport summarizes the result of a migration operation.
type MigrationReport struct {
	Source            string
	Tools             []MigrationTool
	OutputFile        string
	UnsupportedFields []string
	Errors            []string
	DryRun            bool
	GeneratedAt       time.Time
}

// MigrationManager converts mise/asdf configuration to UniRTM format.
//
// Validates Requirements: 21.1, 21.2, 21.3, 21.4, 21.5, 21.6, 21.7
type MigrationManager struct{}

// NewMigrationManager creates a new MigrationManager.
func NewMigrationManager() *MigrationManager {
	return &MigrationManager{}
}

// MigrateFile converts a single mise/asdf configuration file to UniRTM format.
//
// It auto-detects the source format from the filename.
//
// Validates Requirements: 21.1, 21.2, 21.3, 21.6
func (mm *MigrationManager) MigrateFile(ctx context.Context, sourcePath string, outputPath string, dryRun bool) (*MigrationReport, error) {
	report := &MigrationReport{
		Source:      sourcePath,
		OutputFile:  outputPath,
		DryRun:      dryRun,
		GeneratedAt: time.Now(),
	}

	// Detect source format
	base := filepath.Base(sourcePath)
	var tools []MigrationTool
	var unsupported []string
	var envVars map[string]interface{}
	var tasks map[string]config.Task
	var settings config.Settings
	var err error

	switch {
	case base == ".tool-versions" || strings.HasSuffix(base, ".tool-versions"):
		tools, err = mm.parseToolVersions(sourcePath)
		report.Source = string(MigrationSourceToolVersions)
	default: // mise.toml or .mise.toml
		tools, envVars, tasks, settings, unsupported, err = mm.parseMiseToml(sourcePath)
		report.Source = string(MigrationSourceMiseToml)
		report.UnsupportedFields = unsupported
	}

	if err != nil {
		report.Errors = append(report.Errors, err.Error())
		return report, fmt.Errorf("parse source file: %w", err)
	}

	report.Tools = tools

	if len(tools) == 0 && len(envVars) == 0 && len(tasks) == 0 {
		report.Errors = append(report.Errors, "no tools, env vars, or tasks found in source file")
		return report, nil
	}

	logger.Info("Parsed migration source", map[string]interface{}{
		"source":     sourcePath,
		"tool_count": len(tools),
		"env_count":  len(envVars),
		"task_count": len(tasks),
	})

	// Determine output path first to know the target format
	if outputPath == "" {
		outputPath = ".unirtm.toml"
		report.OutputFile = outputPath
	}

	// Generate UniRTM configuration content
	newCfg := &config.Config{
		Tools:    make(config.ToolMap),
		ToolsRaw: make(map[string]interface{}),
		Env:      envVars,
		Tasks:    tasks,
		Settings: settings,
	}

	for _, t := range tools {
		tc := config.ToolConfig{
			Version:  t.Version,
			Backend:  t.Backend,
			Provider: t.Provider,
		}
		newCfg.Tools[t.Name] = tc
		if tc.Backend == "" && tc.Provider == "" {
			newCfg.ToolsRaw[t.Name] = tc.Version
		} else {
			newCfg.ToolsRaw[t.Name] = tc
		}
	}

	content, err := toml.Marshal(newCfg)
	if err != nil {
		return report, fmt.Errorf("marshal unirtm config: %w", err)
	}

	finalContent := "# UniRTM configuration\n# Generated by 'unirtm migrate' — review before use\n\n" + string(content)

	if dryRun {
		logger.Info("[dry-run] Would write UniRTM config", map[string]interface{}{
			"output":  outputPath,
			"content": finalContent,
		})
		return report, nil
	}

	if err := os.WriteFile(outputPath, []byte(finalContent), 0644); err != nil {
		report.Errors = append(report.Errors, fmt.Sprintf("write output: %s", err.Error()))
		return report, fmt.Errorf("write output file: %w", err)
	}

	logger.Info("Migration complete", map[string]interface{}{
		"output":     outputPath,
		"tool_count": len(tools),
	})

	return report, nil
}

// MigrateDirectory scans a directory for mise/asdf config files and migrates them.
//
// Validates Requirement: 21.4
func (mm *MigrationManager) MigrateDirectory(ctx context.Context, dir string, dryRun bool) ([]*MigrationReport, error) {
	candidates := []string{
		filepath.Join(dir, ".mise.toml"),
		filepath.Join(dir, "mise.toml"),
		filepath.Join(dir, ".tool-versions"),
	}

	var reports []*MigrationReport
	for _, candidate := range candidates {
		if _, err := os.Stat(candidate); os.IsNotExist(err) {
			continue
		}
		outputPath := filepath.Join(dir, ".unirtm.toml")
		report, err := mm.MigrateFile(ctx, candidate, outputPath, dryRun)
		if err != nil {
			report.Errors = append(report.Errors, err.Error())
		}
		reports = append(reports, report)
		break // Stop after first found file
	}

	if len(reports) == 0 {
		return nil, fmt.Errorf("no mise or .tool-versions files found in %s", dir)
	}

	return reports, nil
}

// parseToolVersions parses an asdf/mise .tool-versions file.
//
// Format: one tool per line — "<name> <version>"
// Validates Requirement: 21.2
func (mm *MigrationManager) parseToolVersions(path string) ([]MigrationTool, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("open .tool-versions: %w", err)
	}
	defer f.Close()

	var tools []MigrationTool
	scanner := bufio.NewScanner(f)
	lineNum := 0
	for scanner.Scan() {
		lineNum++
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		parts := strings.Fields(line)
		if len(parts) < 2 {
			continue
		}
		tools = append(tools, MigrationTool{
			Name:    parts[0],
			Version: parts[1],
			Source:  MigrationSourceToolVersions,
		})
	}

	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("scan .tool-versions: %w", err)
	}
	return tools, nil
}

// parseMiseToml parses a .mise.toml file and extracts tools, env, tasks and settings.
//
// Validates Requirement: 21.1
func (mm *MigrationManager) parseMiseToml(path string) ([]MigrationTool, map[string]interface{}, map[string]config.Task, config.Settings, []string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, nil, nil, config.Settings{}, nil, fmt.Errorf("read mise.toml: %w", err)
	}

	var raw map[string]interface{}
	if err := toml.Unmarshal(data, &raw); err != nil {
		return nil, nil, nil, config.Settings{}, nil, fmt.Errorf("unmarshal mise.toml: %w", err)
	}

	var tools []MigrationTool
	var unsupported []string
	envVars := make(map[string]interface{})
	tasks := make(map[string]config.Task)
	settings := config.Settings{
		CacheTTL: 86400, // Default 24h
	}

	// 1. Migrate Tools
	if toolsData, ok := raw["tools"].(map[string]interface{}); ok {
		for name, val := range toolsData {
			switch v := val.(type) {
			case string:
				tools = append(tools, MigrationTool{Name: name, Version: v, Source: MigrationSourceMiseToml})
			case map[string]interface{}:
				version, _ := v["version"].(string)
				backend, _ := v["backend"].(string)
				provider, _ := v["provider"].(string)
				if version == "" {
					// Some mise tools might use other fields or be complex.
					// If we can't find a version, skip or warn.
					unsupported = append(unsupported, fmt.Sprintf("tool %q has complex configuration that may be lost", name))
					continue
				}
				tools = append(tools, MigrationTool{
					Name:     name,
					Version:  version,
					Backend:  backend,
					Provider: provider,
					Source:   MigrationSourceMiseToml,
				})
			default:
				unsupported = append(unsupported, fmt.Sprintf("tool %q has unsupported value type %T", name, val))
			}
		}
	}

	// 2. Migrate Env
	if envData, ok := raw["env"].(map[string]interface{}); ok {
		for k, v := range envData {
			if str, ok := v.(string); ok {
				newKey := strings.Replace(k, "MISE_", "UNIRTM_", 1)
				newVal := strings.ReplaceAll(str, "MISE_", "UNIRTM_")
				envVars[newKey] = newVal
			} else {
				unsupported = append(unsupported, fmt.Sprintf("env var %q has non-string value and was skipped", k))
			}
		}
	}

	// 3. Migrate Tasks
	if tasksData, ok := raw["tasks"].(map[string]interface{}); ok {
		for name, val := range tasksData {
			switch v := val.(type) {
			case string:
				tasks[name] = config.Task{Run: v}
			case map[string]interface{}:
				task := config.Task{}
				if run, ok := v["run"].(string); ok {
					task.Run = run
				}
				if desc, ok := v["description"].(string); ok {
					task.Description = desc
				}
				if depends, ok := v["depends"].([]interface{}); ok {
					for _, d := range depends {
						if ds, ok := d.(string); ok {
							task.Depends = append(task.Depends, ds)
						}
					}
				}
				if env, ok := v["env"].(map[string]interface{}); ok {
					task.Env = make(map[string]interface{})
					for ek, ev := range env {
						task.Env[ek] = ev
					}
				}
				if task.Run != "" {
					tasks[name] = task
				}
			}
		}
	}

	// 4. Migrate Settings (partial mapping)
	if settingsData, ok := raw["settings"].(map[string]interface{}); ok {
		if ttl, ok := settingsData["cache_ttl"].(int64); ok {
			settings.CacheTTL = config.DurationOrInt(ttl)
		} else if ttlStr, ok := settingsData["cache_ttl"].(string); ok {
			// Try to parse duration if it's a string like "1h"
			if d, err := time.ParseDuration(ttlStr); err == nil {
				settings.CacheTTL = config.DurationOrInt(d.Seconds())
			}
		}



		if locked, ok := settingsData["locked"].(bool); ok {
			settings.Locked = locked
		}
	}

	return tools, envVars, tasks, settings, unsupported, nil
}

// FormatReport returns a human-readable migration report string.
//
// Validates Requirement: 21.7 (generate migration report)
func (mm *MigrationManager) FormatReport(report *MigrationReport) string {
	var sb strings.Builder

	sb.WriteString("Migration Report\n")
	sb.WriteString(strings.Repeat("─", 40) + "\n")
	sb.WriteString(fmt.Sprintf("Source:  %s\n", report.Source))
	sb.WriteString(fmt.Sprintf("Output:  %s\n", report.OutputFile))
	if report.DryRun {
		sb.WriteString("Mode:    dry-run (no files written)\n")
	}
	sb.WriteString(fmt.Sprintf("Tools:   %d\n", len(report.Tools)))

	if len(report.Tools) > 0 {
		sb.WriteString("\nMigrated tools:\n")
		for _, t := range report.Tools {
			sb.WriteString(fmt.Sprintf("  • %s@%s\n", t.Name, t.Version))
		}
	}

	if len(report.UnsupportedFields) > 0 {
		sb.WriteString("\nWarnings (manual review needed):\n")
		for _, u := range report.UnsupportedFields {
			sb.WriteString(fmt.Sprintf("  ⚠  %s\n", u))
		}
	}

	if len(report.Errors) > 0 {
		sb.WriteString("\nErrors:\n")
		for _, e := range report.Errors {
			sb.WriteString(fmt.Sprintf("  ✗  %s\n", e))
		}
	}

	return sb.String()
}
