// Copyright (c) 2026 SnowdreamTech. All rights reserved.
// Licensed under the MIT License. See LICENSE file in the project root for full license information.

// Package service provides business logic for UniRTM operations.
//
// Shim scripts are thin wrapper scripts placed in the shims directory
// that intercept calls to tools and delegate to the correct version based
// on the active environment settings.
//
// Validates Requirements: 14.1, 14.2, 14.3, 14.4, 14.5, 14.6, 14.7
package service

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"
)

// Generator creates shim scripts for installed tools.
type Generator struct {
	// shimsDir is the directory where shim scripts are written.
	shimsDir string
	// installsDir is the root directory where tools are installed.
	installsDir string
}

// NewGenerator creates a new shim Generator.
func NewGenerator(shimsDir, installsDir string) *Generator {
	return &Generator{
		shimsDir:    shimsDir,
		installsDir: installsDir,
	}
}

// GenerateShim creates a shim script for the given tool.
//
// On Unix systems it creates a bash/sh script; on Windows it creates
// both a .cmd batch file and a .ps1 PowerShell script.
//
// Validates Requirements: 14.1, 14.2, 14.3, 14.4
func (g *Generator) GenerateShim(ctx context.Context, tool string, executables ...string) error {
	if err := os.MkdirAll(g.shimsDir, 0755); err != nil {
		return fmt.Errorf("create shims directory: %w", err)
	}

	if len(executables) == 0 {
		executables = []string{tool}
	}

	for _, exe := range executables {
		// Strip directory prefix if present (e.g. "bin/go" -> "go")
		exeName := filepath.Base(exe)
		
		switch runtime.GOOS {
		case "windows":
			if err := g.generateWindowsShim(tool, exeName); err != nil {
				return err
			}
		default:
			if err := g.generateUnixShim(tool, exeName); err != nil {
				return err
			}
		}
	}
	return nil
}

// RemoveShim removes the shim script(s) for the given tool.
func (g *Generator) RemoveShim(ctx context.Context, tool string) error {
	paths := g.shimPaths(tool)
	var errs []string
	for _, p := range paths {
		if err := os.Remove(p); err != nil && !os.IsNotExist(err) {
			errs = append(errs, err.Error())
		}
	}
	if len(errs) > 0 {
		return fmt.Errorf("remove shim: %s", strings.Join(errs, "; "))
	}
	return nil
}

// ShimExists reports whether a shim script exists for the given tool.
func (g *Generator) ShimExists(tool string) bool {
	paths := g.shimPaths(tool)
	for _, p := range paths {
		if _, err := os.Stat(p); err == nil {
			return true
		}
	}
	return false
}

// ListShims returns all tool names that have shim scripts.
func (g *Generator) ListShims() ([]string, error) {
	entries, err := os.ReadDir(g.shimsDir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("list shims: %w", err)
	}

	seen := make(map[string]bool)
	var tools []string
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		// Strip Windows-specific extensions
		tool := strings.TrimSuffix(strings.TrimSuffix(name, ".cmd"), ".ps1")
		if !seen[tool] {
			seen[tool] = true
			tools = append(tools, tool)
		}
	}
	return tools, nil
}

// shimPaths returns all shim file paths for a tool (platform-dependent).
func (g *Generator) shimPaths(tool string) []string {
	if runtime.GOOS == "windows" {
		return []string{
			filepath.Join(g.shimsDir, tool+".cmd"),
			filepath.Join(g.shimsDir, tool+".ps1"),
		}
	}
	return []string{filepath.Join(g.shimsDir, tool)}
}

// generateUnixShim creates a POSIX-compatible shim script.
//
// The script:
//  1. Detects the active version from UNIRTM_<TOOL>_VERSION or defaults to "current"
//  2. Resolves the tool binary path in the installs directory
//  3. Delegates execution with all original arguments preserved
//  4. Preserves exit codes (Requirement 14.4)
//  5. Provides helpful error when no version is active (Requirement 14.7)
func (g *Generator) generateUnixShim(tool, executable string) error {
	shimPath := filepath.Join(g.shimsDir, executable)

	envVar := toolVersionEnvVar(tool)
	installRoot := filepath.Join(g.installsDir, tool)

	content := fmt.Sprintf(`#!/bin/sh
# UniRTM shim for %s
# Generated by UniRTM — do not edit manually
set -e

# Determine active version
if [ -n "${%s}" ]; then
    UNIRTM_VERSION="${%s}"
elif [ -n "${UNIRTM_ACTIVATION_SCOPE}" ] && [ "${UNIRTM_ACTIVATION_SCOPE}" = "project" ] && \
     [ -f "${UNIRTM_PROJECT_DIR}/.unirtm.toml" ]; then
    # Attempt to read version from project config (requires grep+sed as sh-only)
    UNIRTM_VERSION=$(grep -A1 '\[tools\.%s\]' "${UNIRTM_PROJECT_DIR}/.unirtm.toml" 2>/dev/null | \
                     grep 'version' | sed 's/.*=\s*"\?\([^"]*\)"\?.*/\1/' | head -1)
fi

if [ -z "${UNIRTM_VERSION}" ]; then
    echo "unirtm: no active version of '%s' found." >&2
    echo "  Run: unirtm activate %s <version>" >&2
    echo "  Or:  eval \"\$(unirtm activate)\"" >&2
    exit 1
fi

# Resolve binary path
TOOL_BIN=""
if [ -f "%s/${UNIRTM_VERSION}/bin/%s" ] && [ -x "%s/${UNIRTM_VERSION}/bin/%s" ]; then
    TOOL_BIN="%s/${UNIRTM_VERSION}/bin/%s"
elif [ -f "%s/${UNIRTM_VERSION}/Home/bin/%s" ] && [ -x "%s/${UNIRTM_VERSION}/Home/bin/%s" ]; then
    TOOL_BIN="%s/${UNIRTM_VERSION}/Home/bin/%s"
elif [ -f "%s/${UNIRTM_VERSION}/Contents/Home/bin/%s" ] && [ -x "%s/${UNIRTM_VERSION}/Contents/Home/bin/%s" ]; then
    TOOL_BIN="%s/${UNIRTM_VERSION}/Contents/Home/bin/%s"
elif [ -f "%s/${UNIRTM_VERSION}/%s" ] && [ -x "%s/${UNIRTM_VERSION}/%s" ]; then
    TOOL_BIN="%s/${UNIRTM_VERSION}/%s"
fi

if [ -z "${TOOL_BIN}" ]; then
    echo "unirtm: '%%s@${UNIRTM_VERSION}' is not installed or binary not found." >&2
    echo "  Run: unirtm install %%s ${UNIRTM_VERSION}" >&2
    exit 1
fi

exec "${TOOL_BIN}" "$@"
`,
		executable,
		envVar, envVar,
		tool,
		tool, tool,
		installRoot, executable, installRoot, executable,
		installRoot, executable, installRoot, executable,
		installRoot, executable, installRoot, executable,
		installRoot, executable, installRoot, executable,
		tool,
		tool,
	)

	if err := os.MkdirAll(filepath.Dir(shimPath), 0755); err != nil {
		return fmt.Errorf("create shim directory for %s: %w", tool, err)
	}
	if err := os.WriteFile(shimPath, []byte(content), 0755); err != nil {
		return fmt.Errorf("write unix shim for %s: %w", tool, err)
	}
	return nil
}

// generateWindowsShim creates Windows-compatible shim scripts (batch + PowerShell).
//
// Validates Requirements: 14.1, 14.2, 14.3, 14.4, 14.5, 14.6
func (g *Generator) generateWindowsShim(tool, executable string) error {
	envVar := toolVersionEnvVar(tool)
	installRoot := filepath.Join(g.installsDir, tool)

	cmdContent := fmt.Sprintf(`@echo off
REM UniRTM shim for %s
REM Generated by UniRTM — do not edit manually

if defined %s (
    set "UNIRTM_VERSION=%%%s%%"
)

if not defined UNIRTM_VERSION (
    echo unirtm: no active version of "%s" found. >&2
    echo   Run: unirtm activate %s ^<version^> >&2
    echo   Or:  eval "$(unirtm activate)" >&2
    exit /b 1
)

set "TOOL_BIN="
if exist "%s\%%UNIRTM_VERSION%%\bin\%s" (
    set "TOOL_BIN=%s\%%UNIRTM_VERSION%%\bin\%s"
) else if exist "%s\%%UNIRTM_VERSION\%s" (
    set "TOOL_BIN=%s\%%UNIRTM_VERSION\%s"
)

if not defined TOOL_BIN (
    echo unirtm: "%s@%%UNIRTM_VERSION%%" is not installed or binary not found. >&2
    echo   Run: unirtm install %s %%UNIRTM_VERSION%% >&2
    exit /b 1
)

"%%TOOL_BIN%%" %%*
`,
		executable,
		envVar, envVar,
		tool,
		tool, tool,
		installRoot, executable, installRoot, executable,
		installRoot, executable, installRoot, executable,
		tool,
		tool,
	)

	cmdPath := filepath.Join(g.shimsDir, executable+".cmd")
	if err := os.MkdirAll(filepath.Dir(cmdPath), 0755); err != nil {
		return fmt.Errorf("create shim directory for %s: %w", tool, err)
	}
	if err := os.WriteFile(cmdPath, []byte(cmdContent), 0644); err != nil {
		return fmt.Errorf("write .cmd shim for %s: %w", tool, err)
	}

	// ── PowerShell (.ps1) shim ───────────────────────────────────────────────
	ps1Content := fmt.Sprintf(`
# UniRTM shim for %s
# Generated by UniRTM — do not edit manually

$UnirtmVersion = $env:%s

if (-not $UnirtmVersion -and $env:UNIRTM_ACTIVATION_SCOPE -eq "project") {
    # Simple project config lookup omitted for brevity in PS1 shim
}

if (-not $UnirtmVersion) {
    Write-Error "unirtm: no active version of '%s' found."
    Write-Host "  Run: unirtm activate %s <version>"
    Write-Host "  Or:  eval \"\$(unirtm activate)\""
    exit 1
}

$ToolBin = ""
if (Test-Path "%s\$UnirtmVersion\bin\%s") {
    $ToolBin = "%s\$UnirtmVersion\bin\%s"
} elseif (Test-Path "%s\$UnirtmVersion\%s") {
    $ToolBin = "%s\$UnirtmVersion\%s"
}

if (-not $ToolBin) {
    Write-Error "unirtm: '%s@$UnirtmVersion' is not installed or binary not found."
    Write-Host "  Run: unirtm install %s \$UnirtmVersion"
    exit 1
}

& "$ToolBin" @args
`,
		executable,
		envVar,
		tool,
		tool, tool,
		installRoot, executable, installRoot, executable,
		installRoot, executable, installRoot, executable,
		tool,
		tool,
	)

	ps1Path := filepath.Join(g.shimsDir, executable+".ps1")
	if err := os.MkdirAll(filepath.Dir(ps1Path), 0755); err != nil {
		return fmt.Errorf("create shim directory for %s: %w", tool, err)
	}
	if err := os.WriteFile(ps1Path, []byte(ps1Content), 0644); err != nil {
		return fmt.Errorf("write .ps1 shim for %s: %w", tool, err)
	}

	return nil
}

// toolVersionEnvVar returns the environment variable name for a tool's active version.
// e.g. "node" → "UNIRTM_NODE_VERSION"
func toolVersionEnvVar(tool string) string {
	upper := strings.ToUpper(strings.ReplaceAll(tool, "-", "_"))
	return fmt.Sprintf("UNIRTM_%s_VERSION", upper)
}
