// Copyright (c) 2026 SnowdreamTech. All rights reserved.
// Licensed under the MIT License. See LICENSE file in the project root for full license information.

// Package service provides business logic for UniRTM operations.
//
// Shim scripts are thin wrapper scripts placed in the shims directory
// that intercept calls to tools and delegate to the correct version based
// on the active environment settings.
//
// Validates Requirements: 14.1, 14.2, 14.3, 14.4, 14.5, 14.6, 14.7
package service

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"
)

// Generator creates shim scripts for installed tools.
type Generator struct {
	// shimsDir is the directory where shim scripts are written.
	shimsDir string
	// installsDir is the root directory where tools are installed.
	installsDir string
}

// NewGenerator creates a new shim Generator.
func NewGenerator(shimsDir, installsDir string) *Generator {
	return &Generator{
		shimsDir:    shimsDir,
		installsDir: installsDir,
	}
}

// GenerateShim creates a shim script for the given tool.
//
// On Unix systems it creates a bash/sh script; on Windows it creates
// both a .cmd batch file and a .ps1 PowerShell script.
//
// Validates Requirements: 14.1, 14.2, 14.3, 14.4
func (g *Generator) GenerateShim(ctx context.Context, tool string, executables ...string) error {
	if err := os.MkdirAll(g.shimsDir, 0755); err != nil {
		return fmt.Errorf("create shims directory: %w", err)
	}

	if len(executables) == 0 {
		executables = []string{tool}
	}

	for _, exe := range executables {
		// Flatten shim directory by always using filepath.Base for the filename.
		// This ensures consistency with mise and avoids nested directories in shims/.
		shimName := filepath.Base(exe)
		if shimName == "." || shimName == "/" {
			continue
		}
		
		switch runtime.GOOS {
		case "windows":
			if err := g.generateWindowsShim(tool, shimName); err != nil {
				return err
			}
		default:
			if err := g.generateUnixShim(tool, shimName); err != nil {
				return err
			}
		}
	}
	return nil
}

// RemoveShim removes the shim script(s) for the given tool.
func (g *Generator) RemoveShim(ctx context.Context, tool string) error {
	paths := g.shimPaths(tool)
	var errs []string
	for _, p := range paths {
		if err := os.Remove(p); err != nil && !os.IsNotExist(err) {
			errs = append(errs, err.Error())
		}
	}
	if len(errs) > 0 {
		return fmt.Errorf("remove shim: %s", strings.Join(errs, "; "))
	}
	return nil
}

// ShimExists reports whether a shim script exists for the given tool.
func (g *Generator) ShimExists(tool string) bool {
	paths := g.shimPaths(tool)
	for _, p := range paths {
		if _, err := os.Stat(p); err == nil {
			return true
		}
	}
	return false
}

// ListShims returns all tool names that have shim scripts.
func (g *Generator) ListShims() ([]string, error) {
	entries, err := os.ReadDir(g.shimsDir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("list shims: %w", err)
	}

	seen := make(map[string]bool)
	var tools []string
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		// Strip Windows-specific extensions
		tool := strings.TrimSuffix(strings.TrimSuffix(name, ".cmd"), ".ps1")
		if !seen[tool] {
			seen[tool] = true
			tools = append(tools, tool)
		}
	}
	return tools, nil
}

// shimPaths returns all shim file paths for a tool (platform-dependent).
// It ensures that the shim name is flat by using filepath.Base(tool).
func (g *Generator) shimPaths(tool string) []string {
	// Flatten tool name for lookup to match flat shims directory
	flatName := filepath.Base(tool)
	if runtime.GOOS == "windows" {
		return []string{
			filepath.Join(g.shimsDir, flatName+".cmd"),
			filepath.Join(g.shimsDir, flatName+".ps1"),
		}
	}
	return []string{filepath.Join(g.shimsDir, flatName)}
}

// generateUnixShim creates a POSIX-compatible shim script.
//
// The script:
//  1. Detects the active version from UNIRTM_<TOOL>_VERSION or defaults to "current"
//  2. Resolves the tool binary path in the installs directory
//  3. Delegates execution with all original arguments preserved
//  4. Preserves exit codes (Requirement 14.4)
//  5. Provides helpful error when no version is active (Requirement 14.7)
func (g *Generator) generateUnixShim(tool, executable string) error {
	shimPath := filepath.Join(g.shimsDir, executable)

	envVar := toolVersionEnvVar(tool)
	
	// We check multiple possible install roots to support backends with prefixes (like native-node)
	// and without (like asdf tools).
	installRootBase := g.installsDir
	
	content := fmt.Sprintf(`#!/bin/sh
# UniRTM shim for %[1]s
# Generated by UniRTM — do not edit manually
set -e

# Determine active version
if [ -n "${%[2]s}" ]; then
    UNIRTM_VERSION="${%[2]s}"
else
    # Try to find project directory by searching upwards for .unirtm.toml
    if [ -z "${UNIRTM_PROJECT_DIR}" ]; then
        CUR_DIR="$PWD"
        while [ "$CUR_DIR" != "/" ]; do
            if [ -f "$CUR_DIR/.unirtm.toml" ] || [ -f "$CUR_DIR/unirtm.toml" ]; then
                UNIRTM_PROJECT_DIR="$CUR_DIR"
                break
            fi
            CUR_DIR=$(dirname "$CUR_DIR")
        done
    fi

    if [ -n "${UNIRTM_PROJECT_DIR}" ] && [ -f "${UNIRTM_PROJECT_DIR}/.unirtm.toml" ]; then
    # Attempt to read version from project config
    # 1. Try modern format: tool = "version" under [tools]
    # Supports both plain 'tool' and 'backend:tool' formats
    UNIRTM_VERSION=$(grep -E "^['\"]?([^:\"']+:)?%[3]s['\"]?\s*=" "${UNIRTM_PROJECT_DIR}/.unirtm.toml" 2>/dev/null | \
                     sed "s/.*=[[:space:]]*['\"]//;s/['\"].*//" | head -1)
    
    # 2. Try legacy format: [tools.tool] version = "..."
    if [ -z "${UNIRTM_VERSION}" ]; then
        UNIRTM_VERSION=$(grep -A1 '\[tools\.\([^.\]]\+:\)\?%[3]s\]' "${UNIRTM_PROJECT_DIR}/.unirtm.toml" 2>/dev/null | \
                         grep 'version' | sed "s/.*=[[:space:]]*['\"]//;s/['\"].*//" | head -1)
    fi
fi
fi

if [ -z "${UNIRTM_VERSION}" ]; then
    echo "unirtm: no active version of '%[1]s' found." >&2
    echo "  Run: unirtm activate %[3]s <version>" >&2
    echo "  Or:  eval \"\$(unirtm activate)\"" >&2
    exit 1
fi

# Resolve binary path by checking possible backend-prefixed directories
TOOL_BIN=""
for BACKEND in "" aqua ubi go-pkg cargo npm pipx brew ruby-build; do
    if [ -z "${BACKEND}" ]; then
        DIR="%[4]s/%[3]s/${UNIRTM_VERSION}"
    else
        DIR="%[4]s/${BACKEND}-%[3]s/${UNIRTM_VERSION}"
    fi

    if [ -f "${DIR}/bin/%[1]s" ] && [ -x "${DIR}/bin/%[1]s" ]; then
        TOOL_BIN="${DIR}/bin/%[1]s"
    elif [ -f "${DIR}/Home/bin/%[1]s" ] && [ -x "${DIR}/Home/bin/%[1]s" ]; then
        TOOL_BIN="${DIR}/Home/bin/%[1]s"
    elif [ -f "${DIR}/Contents/Home/bin/%[1]s" ] && [ -x "${DIR}/Contents/Home/bin/%[1]s" ]; then
        TOOL_BIN="${DIR}/Contents/Home/bin/%[1]s"
    elif [ -f "${DIR}/%[1]s" ] && [ -x "${DIR}/%[1]s" ]; then
        TOOL_BIN="${DIR}/%[1]s"
    fi
    
    if [ -n "${TOOL_BIN}" ]; then break; fi
done

if [ -z "${TOOL_BIN}" ]; then
    echo "unirtm: '%[3]s@${UNIRTM_VERSION}' is not installed or binary not found." >&2
    echo "  Run: unirtm install %[3]s ${UNIRTM_VERSION}" >&2
    exit 1
fi

exec "${TOOL_BIN}" "$@"
`,
		executable,
		envVar,
		tool,
		installRootBase,
	)

	if err := os.MkdirAll(filepath.Dir(shimPath), 0755); err != nil {
		return fmt.Errorf("create shim directory for %s: %w", tool, err)
	}
	if err := os.WriteFile(shimPath, []byte(content), 0755); err != nil {
		return fmt.Errorf("write unix shim for %s: %w", tool, err)
	}
	return nil
}

// generateWindowsShim creates Windows-compatible shim scripts (batch + PowerShell).
//
// Validates Requirements: 14.1, 14.2, 14.3, 14.4, 14.5, 14.6
func (g *Generator) generateWindowsShim(tool, executable string) error {
	envVar := toolVersionEnvVar(tool)
	installRootBase := g.installsDir

	cmdContent := fmt.Sprintf(`@echo off
REM UniRTM shim for %[1]s
REM Generated by UniRTM — do not edit manually

if defined %[2]s (
    set "UNIRTM_VERSION=%%%[2]s%%"
)

if not defined UNIRTM_VERSION (
    echo unirtm: no active version of "%[1]s" found. >&2
    echo   Run: unirtm activate %[3]s ^<version^> >&2
    echo   Or:  eval "$(unirtm activate)" >&2
    exit /b 1
)

set "TOOL_BIN="
for %%%%B in (native aqua ubi go-pkg cargo npm pipx brew ruby-build) do (
    set "DIR=%[4]s\%%%%B-%[3]s\%%UNIRTM_VERSION%%"
    if exist "%%DIR%%\bin\%[1]s" (
        set "TOOL_BIN=%%DIR%%\bin\%[1]s"
    ) else if exist "%%DIR%%\%[1]s" (
        set "TOOL_BIN=%%DIR%%\%[1]s"
    )
    if defined TOOL_BIN goto found
)

REM Also check the non-prefixed directory
set "DIR=%[4]s\%[3]s\%%UNIRTM_VERSION%%"
if exist "%%DIR%%\bin\%[1]s" (
    set "TOOL_BIN=%%DIR%%\bin\%[1]s"
) else if exist "%%DIR%%\%[1]s" (
    set "TOOL_BIN=%%DIR%%\%[1]s"
)

:found
if not defined TOOL_BIN (
    echo unirtm: "%[3]s@%%UNIRTM_VERSION%%" is not installed or binary not found. >&2
    echo   Run: unirtm install %[3]s %%UNIRTM_VERSION%% >&2
    exit /b 1
)

"%%TOOL_BIN%%" %%*
`,
		executable,
		envVar,
		tool,
		installRootBase,
	)

	cmdPath := filepath.Join(g.shimsDir, executable+".cmd")
	if err := os.MkdirAll(filepath.Dir(cmdPath), 0755); err != nil {
		return fmt.Errorf("create shim directory for %s: %w", tool, err)
	}
	if err := os.WriteFile(cmdPath, []byte(cmdContent), 0644); err != nil {
		return fmt.Errorf("write .cmd shim for %s: %w", tool, err)
	}

	// ── PowerShell (.ps1) shim ───────────────────────────────────────────────
	ps1Content := fmt.Sprintf(`
# UniRTM shim for %[1]s
# Generated by UniRTM — do not edit manually

$UnirtmVersion = $env:%[2]s

if (-not $UnirtmVersion -and $env:UNIRTM_ACTIVATION_SCOPE -eq "project") {
    # Simple project config lookup
    if (Test-Path "$env:UNIRTM_PROJECT_DIR\.unirtm.toml") {
        $Content = Get-Content "$env:UNIRTM_PROJECT_DIR\.unirtm.toml"
        $Line = $Content | Where-Object { $_ -match "^['\"]?%[3]s['\"]?\s*=" } | Select-Object -First 1
        if ($Line -match '=\s*["'\'']([^"'\'']*)["'\'']') {
            $UnirtmVersion = $Matches[1]
        }
    }
}

if (-not $UnirtmVersion) {
    Write-Error "unirtm: no active version of '%[1]s' found."
    Write-Host "  Run: unirtm activate %[3]s <version>"
    Write-Host "  Or:  eval \"\$(unirtm activate)\""
    exit 1
}

$ToolBin = ""
$Backends = @("", "native", "aqua", "ubi", "go-pkg", "cargo", "npm", "pipx", "brew", "ruby-build")
foreach ($Backend in $Backends) {
    if ($Backend -eq "") {
        $Dir = "%[4]s\%[3]s\$UnirtmVersion"
    } else {
        $Dir = "%[4]s\$Backend-%[3]s\$UnirtmVersion"
    }

    if (Test-Path "$Dir\bin\%[1]s") {
        $ToolBin = "$Dir\bin\%[1]s"
        break
    } elseif (Test-Path "$Dir\%[1]s") {
        $ToolBin = "$Dir\%[1]s"
        break
    }
}

if (-not $ToolBin) {
    Write-Error "unirtm: '%[3]s@$UnirtmVersion' is not installed or binary not found."
    Write-Host "  Run: unirtm install %[3]s \$UnirtmVersion"
    exit 1
}

& "$ToolBin" @args
`,
		executable,
		envVar,
		tool,
		installRootBase,
	)

	ps1Path := filepath.Join(g.shimsDir, executable+".ps1")
	if err := os.MkdirAll(filepath.Dir(ps1Path), 0755); err != nil {
		return fmt.Errorf("create shim directory for %s: %w", tool, err)
	}
	if err := os.WriteFile(ps1Path, []byte(ps1Content), 0644); err != nil {
		return fmt.Errorf("write .ps1 shim for %s: %w", tool, err)
	}

	return nil
}

// toolVersionEnvVar returns the environment variable name for a tool's active version.
// e.g. "node" → "UNIRTM_NODE_VERSION"
func toolVersionEnvVar(tool string) string {
	upper := strings.ToUpper(strings.ReplaceAll(tool, "-", "_"))
	return fmt.Sprintf("UNIRTM_%s_VERSION", upper)
}
