// Code generated by test generator. DO NOT EDIT.
package backend

import (
	"testing"
)

func TestHTTPBackend_GenMethods(t *testing.T) {
	b := NewHTTPBackend()
	if b == nil {
		t.Fatal("backend is nil")
	}

	_ = b.Name()
	_ = b.Dependencies()
	_ = b.SupportsChecksum()
	_ = b.SupportsGPG()
	_ = b.AttestationType()
	_ = b.IsRecommended()
	_ = b.IsScriptless()
	_ = b.GetReach()
	_ = b.IsStable()
	_ = b.SupportsOffline()
}
