// Copyright (c) 2026 SnowdreamTech. All rights reserved.
// Licensed under the MIT License. See LICENSE file in the project root for full license information.

package provider

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/pterm/pterm"

	"github.com/snowdreamtech/unirtm/internal/cli/output"
)

// ContainerProvider implements the Provider interface for container-backed tools.
type ContainerProvider struct {
	name string
}

// NewContainerProvider creates a new ContainerProvider.
func NewContainerProvider(name string) *ContainerProvider {
	return &ContainerProvider{name: name}
}

// Name returns the provider identifier.
func (p *ContainerProvider) Name() string {
	return p.name
}

// Install performs the environment check, image pull, and wrapper script generation.
func (p *ContainerProvider) Install(ctx context.Context, tool string, installPath string, artifactPath string, version string) error {
	// 1. Environment Detection: Check for podman, docker, nerdctl
	engines := []string{"podman", "docker", "nerdctl"}
	var activeEngine string

	for _, engine := range engines {
		if path, err := exec.LookPath(engine); err == nil && path != "" {
			activeEngine = engine
			break
		}
	}

	if activeEngine == "" {
		// No container engine found. Abort and recommend.
		recommendation := "Docker Desktop or Podman"
		if runtime.GOOS == "linux" {
			recommendation = "podman or docker"
		}
		output.Errorf("✖ No container engine found. Please install %s to use container tools.", recommendation)
		return fmt.Errorf("container engine not found in PATH")
	}

	// 2. Construct image string
	// Tool contains registry+image (e.g. ghcr.io/aquasec/trivy)
	image := tool
	if strings.HasPrefix(version, "sha256:") {
		image = fmt.Sprintf("%s@%s", tool, version)
	} else if version != "" && version != "latest" {
		image = fmt.Sprintf("%s:%s", tool, version)
	} else if version == "latest" {
		image = fmt.Sprintf("%s:latest", tool)
	}

	// 3. Pull the image
	pterm.FgCyan.Printf("ℹ Pulling image: %s using %s...\n", image, activeEngine)
	cmd := exec.CommandContext(ctx, activeEngine, "pull", image)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("failed to pull container image %s: %w", image, err)
	}

	// 4. Generate wrapper script in the bin directory
	binDir := filepath.Join(installPath, "bin")
	if err := os.MkdirAll(binDir, 0755); err != nil {
		return fmt.Errorf("failed to create bin directory: %w", err)
	}

	// Extract the basename of the tool to be the command name
	// E.g., ghcr.io/aquasec/trivy -> trivy
	parts := strings.Split(tool, "/")
	basename := parts[len(parts)-1]

	wrapperPath := filepath.Join(binDir, basename)
	
	if runtime.GOOS == "windows" {
		wrapperPath += ".cmd"
		// Simple Windows batch wrapper
		scriptContent := fmt.Sprintf(`@echo off
REM Auto-generated by UniRTM Container Provider
set CONTAINER_ENGINE=%s
set IMAGE=%s

set TTY_ARG=
REM Note: Windows TTY detection in batch is complex, omitting -t for now to ensure compatibility
REM but users can pass -t via arguments if needed.

"%%CONTAINER_ENGINE%%" run --rm -i %%TTY_ARG%% -v "%%CD%%:%%CD%%" -w "%%CD%%" "%%IMAGE%%" %%*
`, activeEngine, image)
		if err := os.WriteFile(wrapperPath, []byte(scriptContent), 0755); err != nil {
			return fmt.Errorf("failed to write wrapper script: %w", err)
		}
	} else {
		// Unix shell wrapper
		scriptContent := fmt.Sprintf(`#!/bin/sh
# Auto-generated by UniRTM Container Provider
CONTAINER_ENGINE="%s"
IMAGE="%s"

TTY_ARG=""
if [ -t 0 ]; then
    TTY_ARG="-t"
fi

exec "$CONTAINER_ENGINE" run --rm -i $TTY_ARG \
    -v "$PWD:$PWD" \
    -w "$PWD" \
    "$IMAGE" "$@"
`, activeEngine, image)
		if err := os.WriteFile(wrapperPath, []byte(scriptContent), 0755); err != nil {
			return fmt.Errorf("failed to write wrapper script: %w", err)
		}
	}

	return nil
}

func (p *ContainerProvider) PostInstall(ctx context.Context, tool string, installPath string, version string) error {
	return nil
}

func (p *ContainerProvider) GenerateShims(tool string, installPath string, version string) (map[string]string, error) {
	// The shims are actually generated by the global shim manager based on the executables returned by ListExecutables.
	// This method in the Provider interface is mostly for customized shim logic.
	// Returning an empty map tells the caller to proceed with normal generation.
	return make(map[string]string), nil
}

func (p *ContainerProvider) DetectVersion(ctx context.Context, tool string, installPath string) (string, error) {
	// Since we wrap the image in a script, version detection could be tricky without spinning up the container.
	// But in standard UniRTM flow, this is often used for generic version checks.
	// For now, return unknown.
	return "unknown", nil
}

func (p *ContainerProvider) ListExecutables(tool string, installPath string, version string) ([]string, error) {
	parts := strings.Split(tool, "/")
	basename := parts[len(parts)-1]
	
	if runtime.GOOS == "windows" {
		return []string{basename + ".cmd"}, nil
	}
	return []string{basename}, nil
}

func (p *ContainerProvider) GetBinPaths(tool string, installPath string, version string) ([]string, error) {
	return []string{filepath.Join(installPath, "bin")}, nil
}

func (p *ContainerProvider) GetEnvVars(tool string, installPath string, version string) (map[string]string, error) {
	return make(map[string]string), nil
}

func (p *ContainerProvider) Uninstall(ctx context.Context, tool string, installPath string, version string) error {
	// We do not delete the image automatically because it might be used by other tags or directly by the user.
	return nil
}
