// Code generated by test generator. DO NOT EDIT.
package provider

import (
	"context"
	"os"
	"path/filepath"
	"testing"
)

func TestGemProvider_GenMethods(t *testing.T) {
	p := NewGemProvider()
	ctx := context.Background()
	installPath := filepath.Join(t.TempDir(), "gem")
	version := "1.0.0"
	tool := "gem"
	artifactPath := "/tmp/dummy"

	if p == nil {
		t.Fatal("provider is nil")
	}

	_ = p.Name()

	// skip network installers Install for now to avoid hanging tests
	if "gem" != "npm" && "gem" != "go_pkg" && "gem" != "spm" && "gem" != "gem" && "gem" != "cargo" {
		_ = p.Install(ctx, tool, installPath, artifactPath, version)
	}

	_ = p.PostInstall(ctx, tool, installPath, version)
	_, _ = p.GetEnvVars(tool, installPath, version)
	_, _ = p.ListExecutables(tool, installPath, version)
	_, _ = p.GenerateShims(tool, installPath, version)

	_ = os.MkdirAll(filepath.Join(installPath, "bin"), 0755)
	_, _ = p.DetectVersion(ctx, tool, installPath)
	_, _ = p.GetBinPaths(tool, installPath, version)
	_ = p.Uninstall(ctx, tool, installPath, version)
}
